version: '3'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e8b50fddddf04ee439f12851f5275222

  feed:
    image: 'btclinkgrt/quorum-feed'
    command: bash -c "yarn start-prod"
    restart: 'always'
    ports:
      - '6090:9000'
    volumes:
      - ./config.js:/server/config.js:ro
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    depends_on:
      - postgres

  nginx:
    image: nginx
    restart: 'always'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/mysite.template:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: ./run_nginx.sh
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
